a = float(input("Enter 1st number:"))
b = float(input("Enter 2nd number:"))

print("Addition:",a+b)
print("Substraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("Exponentional:",a**b)
print("Modulas:",a%b)
print("Floor Division:",a//b)
